name: Feature Request
description: Suggest an idea for Xiaoqinglong
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: What would you like Xiaoqinglong to do?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why is this feature useful? How would it help you?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds?
